version: '3'

services:
  backend:
    build: .

    image: node:18
    depends_on:
      - db

    ports:
      - "3001:3001"
    
    environment:
      DATABASE_URL: "postgres://postgres:1234@localhost:5432/ng-cash"
      NODE_ENV: "development"

    networks:
      - ng-cash-application
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "49555:5432"

    networks:
      - ng-cash-application

networks:
  ng-cash-application:
    driver: bridge
